### ISSUE TITLE
SNP annotation files

### ISSUE THREAD

**Issue by cybluetree** [AprilWei001/NIM#4]
Hi, this is a wonderful study! In the 'SNP annotation' section, it's mentioned that the output file names for ancestry, MAF, and LD-score are indicated by .anc, .maf, and .ld, respectively. However, it seems these files haven't been deposited in the repository yet. Will they be made available later? Thanks!

**Comment by AprilWei001** [comment]
Hello, I just pushed writeAnnot.m and writeAnnotMAFLD.m, which should help you with SNP annotation. Let me know if you need anything else.
